# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_image:
    docker:
      - image: docker:17.11.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Auth GCP Container Registry
          command: |
            echo $vnet_core_gcp_service_account | docker login --username _json_key --password-stdin https://eu.gcr.io
      - run:
          name: Build image
          command: |
            docker build --tag eu.gcr.io/vnet-core/circleci/automation_framework_image:${CIRCLE_BRANCH//\//_} \
              --label org.label-schema.vcs-ref=$CIRCLE_SHA1 \
              --label org.label-schema.vcs-url=$CIRCLE_REPOSITORY_URL \
              --label org.label-schema.schema-version="1.0" \
              .
      - run:
          name: Push image to registry
          command: |
            docker push eu.gcr.io/vnet-core/circleci/automation_framework_image:${CIRCLE_BRANCH//\//_}
      - persist_to_workspace:
          root: /
          paths:
            - pushed_images.txt
      - store_artifacts:
          path: /pushed_images.txt

workflows:
  version: 2
  automation_framework:
    jobs:
      - build_image:
          context: vnet
